### ISSUE TITLE
Add RTL-SDR BLOG V4 driver support

### ISSUE THREAD

**Issue by mannkeithc** [KentuckyFriedData/SDRPlusPlus-Mac_ARM64#1]
I have installed your SDR++ arm64 build on my M2 MacBook Pro and it works fine with my NooElec NESDR v5 and RTL-SDR BLOG v3 SDR radio dongles.

I recently purchased an RTL-SDR BLOG v4 SDR dongle. This has extended spectrum coverage to include HF / SW bands down to 500 Hz but requires a new driver to support its revised architecture. The new driver is backwards compatible with prior RTL-SDR Blog versions and generic RTL-SDR dongles.

Details are given on the following GitHub site:
https://github.com/rtlsdrblog/rtl-sdr-blog

Would it be possible to update your Mac OS arm64 build to include the latest RTL-SDR driver with RRL-SDR BLOG v4 dongle support?

**Comment by KentuckyFriedData** [comment]
Just pulled from Alexandre's repo and the driver should be in the latest build :)
